# This file is a template, and might need editing before it works on your project.
# Unofficial language image. Look for the different tagged releases at:
# https://hub.docker.com/r/scorpil/rust/tags/
image: "scorpil/rust:stable"
image: "scorpil/rust:beta"
image: "scorpil/rust:nightly"

# Test the build of the project
build:
  script:
    - rustc --version && cargo --version      # Print version info for debugging
    - cargo build --verbose

# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version      # Print version info for debugging
    - cargo test --verbose --jobs 1 --release # Don't paralize to make errors more readable
